name: travel_assistant_ai
repository: https://github.com/JKhanh/travel-assistant-ai

packages:
  - .
  - packages/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  analyze:
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
    run: dart analyze --fatal-infos
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  format:
    description: |
      Run `dart format` in all packages.
    run: dart format --set-exit-if-changed .
    exec:
      concurrency: 5
      failFast: true

  test:
    description: |
      Run `flutter test` in all packages.
    run: flutter test --no-pub --coverage
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true

  build:
    description: |
      Run `flutter build` for all supported platforms.
    run: |
      flutter build apk --debug
      flutter build web --debug
    exec:
      concurrency: 1
      failFast: true

  clean:
    description: |
      Clean things very deeply with `flutter clean`.
    run: flutter clean
    exec:
      concurrency: 5
      failFast: true

  pub-get:
    description: |
      Run `flutter pub get` in all packages.
    run: flutter pub get
    exec:
      concurrency: 5
      failFast: true

  upgrade:
    description: |
      Run `flutter pub upgrade` in all packages.
    run: flutter pub upgrade
    exec:
      concurrency: 5
      failFast: true

  lint:
    description: |
      Run `flutter analyze` and `dart format --set-exit-if-changed` in all packages.
    run: |
      flutter analyze --fatal-infos
      dart format --set-exit-if-changed .
    exec:
      concurrency: 5
      failFast: true

ide:
  intellij:
    enabled: false
